// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUA_Va5GAi8TjFQljlOnmW6igBiHqfSac',
    appId: '1:936782351432:android:072bfc70737280fa6a5c7d',
    messagingSenderId: '936782351432',
    projectId: 'electra-3b6eb',
    storageBucket: 'electra-3b6eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2UW2iHOzMHO79VSiCBEyPiytZwkpc2CA',
    appId: '1:936782351432:ios:f67f7e35212d83536a5c7d',
    messagingSenderId: '936782351432',
    projectId: 'electra-3b6eb',
    storageBucket: 'electra-3b6eb.firebasestorage.app',
    iosBundleId: 'com.electra.app',
  );
}
