// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXpUIK6oBNXE3DhhYT7qJp3NDajnRbN54',
    appId: '1:420625008233:android:67a9dae343fe121dd144f8',
    messagingSenderId: '420625008233',
    projectId: 'qleo-1eeac',
    storageBucket: 'qleo-1eeac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoKuOmdI1YPpo0b8F2oqJ_Ali2zritlZg',
    appId: '1:420625008233:ios:f19293aa9c47444dd144f8',
    messagingSenderId: '420625008233',
    projectId: 'qleo-1eeac',
    storageBucket: 'qleo-1eeac.firebasestorage.app',
    iosBundleId: 'com.app.qleo',
  );
}
