// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTTpW4oAWRb2aSFZDw9ZFwXr8yBvlJQEI',
    appId: '1:738537854047:android:75bf9ee2d10e44df8d37ea',
    messagingSenderId: '738537854047',
    projectId: 'minata-51ccd',
    storageBucket: 'minata-51ccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpN-CJ3je3E5O_Vyl4YVpuKb9lVtokGOg',
    appId: '1:738537854047:ios:6d48b1b5089e426b8d37ea',
    messagingSenderId: '738537854047',
    projectId: 'minata-51ccd',
    storageBucket: 'minata-51ccd.firebasestorage.app',
    iosBundleId: 'com.minata.app',
  );
}
