import 'package:minata/app.dart';
import 'package:minata/service_locator.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:minata/common/blocs/app_bloc_observer.dart';
import 'package:hydrated_bloc/hydrated_bloc.dart';
import 'package:path_provider/path_provider.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:minata/core/configs/env.dart';
import 'package:intl/date_symbol_data_local.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:minata/core/services/fcm_service.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // For debugging Bloc events
  Bloc.observer = AppBlocObserver();

  // Initialize HydratedBloc storage (Mobile only)
  final tempDir = await getApplicationDocumentsDirectory();
  HydratedBloc.storage = await HydratedStorage.build(
    storageDirectory: HydratedStorageDirectory(tempDir.path),
  );

  // Set preferred orientations
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  // Detect which environment to load
  const env = String.fromEnvironment('ENV', defaultValue: 'development');
  final fileName = env == 'production'
      ? '.env.production'
      : env == 'staging'
      ? '.env.staging'
      : '.env';

  await dotenv.load(fileName: fileName);

  // Optional: Print env in debug mode
  if (env == 'development') {
    Env.debugPrintAll();
  }

  // 1. Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // 2. Register the background handler BEFORE runApp (FCM requirement)
  FcmService.registerBackgroundHandler();

  await initializeDateFormatting();
  // Initialize dependency injection
  await init(); // DI (Service Locator)

  runApp(const MainApp());
}
